# Generated by Django 5.2.6 on 2025-09-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile/')),
                ('badge_icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('description_secondary', models.TextField(blank=True)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('resume_link', models.URLField(blank=True)),
                ('talk_link', models.URLField(blank=True)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('client_satisfaction', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
