# Generated by Django 5.2.6 on 2025-09-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='badge_icon',
        ),
    ]
