# Generated by Django 5.2.6 on 2025-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_about_badge_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
