# Generated by Django 5.2.6 on 2025-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='skills/')),
                ('proficiency', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
