# Generated by Django 5.2.6 on 2025-09-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
