# Generated by Django 5.2.6 on 2025-09-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_skill_proficiency_skill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('photography', 'Photography'), ('design', 'Design'), ('automotive', 'Automotive'), ('nature', 'Nature')], max_length=20)),
            ],
        ),
    ]
