# Generated by Django 5.2.6 on 2025-09-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
