# Generated by Django 5.2.6 on 2025-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
