# Generated by Django 5.2.6 on 2025-09-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_contact_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactMessage',
        ),
    ]
