# Generated by Django 5.2.6 on 2025-10-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_rename_contact_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
