# Generated by Django 5.2.6 on 2025-10-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_service_contact_support_service_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, upload_to='services/'),
        ),
    ]
