# Generated by Django 5.2.6 on 2025-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_service_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Hi, it's me", max_length=200)),
                ('subtitle', models.CharField(default='Subash Dhami', max_length=200)),
                ('description', models.TextField(default='Passionate Python Django developer creating dynamic web applications that blend clean code with user-friendly design. Let’s turn your ideas into reality.')),
                ('profile_image', models.ImageField(default='static/img/profile/profile.png', upload_to='profile/')),
                ('background_image', models.ImageField(blank=True, upload_to='background/')),
            ],
        ),
    ]
