# Generated by Django 5.2.6 on 2025-10-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='indexhero',
        ),
    ]
