# Generated by Django 5.2.6 on 2025-10-15 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_rename_index_indexhero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('content', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('read_time', models.CharField(default='1 min read', max_length=50)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
