# Generated by Django 5.2.6 on 2025-10-15 19:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('short_description', models.TextField(blank=True)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='SubArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_articles/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('read_time', models.CharField(default='1 min read', max_length=50)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('main_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_articles', to='index.mainarticle')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
